# Permalinks
permalink: pretty

# Setup
title: pavliuko
url: http://pavliuko.github.io/about/
paginate: 10
# baseurl: http://pavliuko.github.io/about/
paginate_path: "/blog/:num/"
highlighter: rouge

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: compressed

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Pages list
pages_list:
  Blog: "/blog"

author:
  name: Oleksandr Pavliuk
  url: http://pavliuko.github.io/about/
  email: pavliuk.aleksandr@gmail.com

# Custom vars
version: 3.0.0
